# Generated by Django 3.0.6 on 2020-05-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_number', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('in_dtm', models.DateTimeField(auto_now_add=True)),
                ('update_dtm', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
